# backend/models/embed_config.py
"""
Embed configuration model for embeddable pages.
Allows users to embed full voice assistant page on their websites.
"""

import uuid
from sqlalchemy import Column, String, Boolean, Integer, ForeignKey, DateTime, JSON
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from backend.models.base import Base, BaseModel

class EmbedConfig(Base, BaseModel):
    """
    Configuration for embeddable voice assistant pages.
    Each config has unique embed_code that maps to specific assistant.
    """
    __tablename__ = "embed_configs"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    assistant_id = Column(UUID(as_uuid=True), ForeignKey("assistant_configs.id", ondelete="CASCADE"), nullable=False)
    
    # Unique embed code (auto-generated by trigger)
    embed_code = Column(String(20), unique=True, nullable=False, index=True)
    
    # Optional customization
    custom_name = Column(String(100), nullable=True)
    custom_settings = Column(JSON, nullable=True, default={})
    
    # Statistics
    total_views = Column(Integer, default=0)
    last_accessed_at = Column(DateTime(timezone=True), nullable=True)
    
    # Status
    is_active = Column(Boolean, default=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Relationships
    user = relationship("User")
    assistant = relationship("AssistantConfig")
    
    def __repr__(self):
        return f"<EmbedConfig(code={self.embed_code}, assistant={self.assistant_id})>"
    
    def to_dict(self):
        """Convert to dict with string IDs"""
        data = super().to_dict()
        data["id"] = str(data["id"])
        data["user_id"] = str(data["user_id"])
        data["assistant_id"] = str(data["assistant_id"])
        return data
    
    def get_embed_url(self, base_url: str = "https://voicyfy.ru") -> str:
        """Get full embed URL"""
        return f"{base_url}/api/embeds/embed/{self.embed_code}"

    def get_iframe_code(self, width: str = "100%", height: str = "800px") -> str:
        """Get ready-to-use iframe HTML code"""
        url = self.get_embed_url()
        return f'''<iframe
    src="{url}"
    width="{width}"
    height="{height}"
    frameborder="0"
    allow="microphone"
    style="border-radius: 16px; box-shadow: 0 4px 16px rgba(0,0,0,0.1);">
</iframe>'''
    
    def increment_views(self, db_session):
        """Increment view counter"""
        self.total_views += 1
        self.last_accessed_at = func.now()
        db_session.commit()
